"""Alter Student model table name to auth_students and add department field.

Generated by assistant to map the Student model to the `auth_students` table and add a
department column. Running migrations will rename the table (if necessary) and add the
new column. The department field allows NULL so this migration is safe on existing rows.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='auth_students',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
