# Generated by Django 4.2.25 on 2025-11-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_material_description_alter_section_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('semester_gpa', models.FloatField(blank=True, null=True)),
                ('cumulative_gpa', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='courses.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='courses.student')),
            ],
            options={
                'verbose_name': 'رصد درجة',
                'verbose_name_plural': 'رصد الدرجات',
                'db_table': 'grade_records',
                'unique_together': {('student', 'material', 'semester', 'year')},
            },
        ),
    ]
