# Generated by Django 4.2.25 on 2025-11-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_graderecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_for', to='courses.material')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_of', to='courses.material')),
            ],
            options={
                'verbose_name': 'أسبقية مادة',
                'verbose_name_plural': 'أسبقيات المواد',
                'db_table': 'material_prerequisites',
                'unique_together': {('material', 'prerequisite')},
            },
        ),
    ]
