# Generated by Django 4.2.25 on 2025-11-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_materialprerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialprerequisite',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_prerequisite_of', to='courses.material'),
        ),
    ]
