# Generated by Django 4.2.25 on 2025-11-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_materialprerequisite_prerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50, verbose_name='المجموعة')),
                ('room', models.CharField(max_length=50, verbose_name='القاعة')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'السبت'), (2, 'الأحد'), (3, 'الاثنين'), (4, 'الثلاثاء'), (5, 'الأربعاء'), (6, 'الخميس')], verbose_name='اليوم')),
                ('time', models.PositiveSmallIntegerField(choices=[(0, '08:00 - 10:00'), (1, '10:00 - 12:00'), (2, '12:00 - 14:00'), (3, '14:00 - 16:00'), (4, '16:00 - 18:00')], verbose_name='الوقت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.material', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'محاضرة',
                'verbose_name_plural': 'المحاضرات',
                'db_table': 'lectures',
                'unique_together': {('material', 'group', 'day', 'time')},
            },
        ),
    ]
